
SET(CMAKE_AUTOMOC ON)
SET(CMAKE_AUTORCC ON)
SET(CMAKE_AUTOUIC ON)

SET(Qt6_CMAKE_DIRS      ${CPP_DIR}/lib/qt6/lib/cmake)
SUB_DIRS(QT6_PACKAGE_TARGET ${Qt6_CMAKE_DIRS})
FOREACH(QT6_PACKAGE ${QT6_PACKAGE_TARGET})
    SET(${QT6_PACKAGE}_DIR "${Qt6_CMAKE_DIRS}/${QT6_PACKAGE}")
ENDFOREACH(QT6_PACKAGE)

FIND_PACKAGE(Qt6 COMPONENTS Core Gui Widgets REQUIRED PrintSupport Network
        #        Svg
        )

LINK_LIBRARIES(Qt6::Core Qt6::Gui Qt6::Widgets Qt6::PrintSupport Qt6::Network
        #            Qt6::Svg
        )