
MACRO(OBJCT_TEMPLATE ObjDir)
    message(STATUS "")
    message(STATUS "PROJECT: ${PROJECT_NAME}")
    message(STATUS "")
    CUR_DIR(DirName ${ObjDir})
    SET(OUTPUT_DIRS  ${CPP_BIN_DIR}/${DirName})
    SET(RES_DIRS  ${CPP_RES_DIR}/${DirName})
    SET(UNSET_VARIABLES  TARGET_SRC_DIRS TARGET_RES_DIRS TARGET_OUTPUT_DIRS TARGET_INCLUDE_DIRS TARGET_SOURCES)
    SUB_DIRS(SOURCE_DIRS ${ObjDir})
    foreach(EXAMPLE ${SOURCE_DIRS})
        foreach(UNSET_TARGET ${UNSET_VARIABLES})
            unset(${UNSET_TARGET})
        endforeach(UNSET_TARGET)
        SET(TARGET_SRC_DIRS  ${ObjDir}/${EXAMPLE})
        SET(TARGET_RES_DIRS  ${RES_DIRS}/${EXAMPLE})
        SET(TARGET_OUTPUT_DIRS  ${OUTPUT_DIRS}/${EXAMPLE})
        set(TARGET_INCLUDE_DIRS ${ObjDir}/${EXAMPLE})
        string(REPLACE "-" ";" Name ${EXAMPLE})
        list(GET Name 1 LOC_TARGET)
        string(CONCAT TARGET "${PROJECT_NAME}-${LOC_TARGET}")
        message(STATUS "TARGET: ${TARGET}")
        aux_source_directory(${TARGET_SRC_DIRS} TARGET_SOURCES)
        add_executable(${TARGET} ${TARGET_SOURCES} ${SOURCES})
        target_include_directories(${TARGET} PRIVATE ${TARGET_INCLUDE_DIRS})
        set_target_properties(${TARGET} PROPERTIES
                CMAKE_DEBUG_POSTFIX         "_d"
                ARCHIVE_OUTPUT_DIRECTORY    "${TARGET_OUTPUT_DIRS}"
                LIBRARY_OUTPUT_DIRECTORY    "${TARGET_OUTPUT_DIRS}"
                RUNTIME_OUTPUT_DIRECTORY    "${TARGET_OUTPUT_DIRS}"
                )
        if(IS_DIRECTORY ${TARGET_RES_DIRS})
            unset(TARGET_ResFiles)
            file(GLOB TARGET_ResFiles "${TARGET_RES_DIRS}/*")
            file(COPY ${TARGET_ResFiles} DESTINATION ${TARGET_OUTPUT_DIRS})
        else()
            #        message("NOT EXiSTS RES_DIR ${RES_DIRS}/${TARGET}")
        endif()
    endforeach(EXAMPLE)
    message(STATUS "")
ENDMACRO(OBJCT_TEMPLATE)
